kind: BuildConfig
apiVersion: v1
metadata:
  name: self-assessment-api-pipeline
  labels:
    app: self-assessment-api-pipeline
spec:
  source:
    git:
      ref: "dev"
      uri: "https://github.com/my-dha-covid19/self-assessment-api.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile 