kind: BuildConfig
apiVersion: v1
metadata:
  name: workgroup-pipeline
  labels:
    app: workgroup-pipeline
spec:
  source:
    git:
      ref: "dev"
      uri: "https://github.com/my-dha-covid19/workgroup.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile 